---
output: 
  md_document:
    variant: markdown_github
    toc: yes
---

## My directory of R packages for data analysis and visualization, Bayesian statistics, mapping, GIS, climate, Species Distribution Modelling, ecology, biogeography, evolution, reproducible science...

Updated `r as.character(Sys.Date())`

### Assumption tests
* [car] () avPlot (influential data), crPlot (linearity), linearHypothesis, ncvTest (heteroscedasticity test for lm), influencePlot (to detect outliers, better than Cooks distance in plot), outlierTest, leveragePlots, qqPlot (normality), vif
* [fit.models] ()
* [lmtest] ()
* [nullabor] () graphical inferences (e.g. qq plots)
* [mvinfluence] ()
* [LogisticDx] ()
* [gof] () Cumres for lm and glm
* [hydroGOF] ()
* [intRegGOF] () lm, glm, nls
* [qvlma] () lm

### Causation
* [bnlearn] ()
* [causaleffect] ()
* [causalFX] ()
* [causalsens] ()
* [causalTree] () heterogeneous subgroup treatment effects by CART
* [causalGAM] ()
* [CovSel] ()
* [CompareCausalNetworks] () backShift, CAM, InvariantCausalPrediction, pcalg
* [ParallelPC] ()
* [PCovR] Principle covariates regression ()
* [SID] ()
* [treatSens] () lm with binary or continuous treatments
* [wfe] () longitudinal data

### Collinearity (VIF>10, only for explanation): reduced by centering
* [ridge]()
* [bestglm]()
* [yhat] () dominance analysis
* [rf] ()
* [pcareg] ()
* [penalized] ()
* [perturb] ()
* [pls] () pcr

### Importance
* [Boruta] () rf
* [multiPIM] () Variable Importance Analysis with Population Intervention Models using TMLE
* [relaimpo]() Relative importance of predictors
* [AICcmodavg] ()
* [MuMIn] ()
* [rms] () plot(anova(f), what='proportion chisq')
* [yhat] () Interpreting Regression Effects
* [vita] () Variable Importance Testing Approaches

### Feature selection (only for prediction)
* [AICcmodavg] () Model selection and multimodel inference
* [bestglm] ()
* [glmulti]() Model selection and multimodel inference, for glm & survival
* [SIS] () Sure Independence Screening for HD1 models, for glm & survival
* [subselect] ()

### Ensemble or model averaging:
* [caretEnsemble] ()
* [MuMIn]() Model selection and averaging
* [medley] () blending predictive models
* [subsemble] ()
* [superlearner] ()

#### for binary Y:
* [VariableSelection] () Identify the appropriate set of predictors of a binary outcome

#### for lm:
* [BayesVarSel] ()
* [CovSel] () Model-Free Covariate or confounder Selection for explanation or causation
* [leaps] () regression subset selection

#### for survival:
[ipred] () indirect classification and bagging for classification, regression and survival
[ranger] rf for HD1 data
[rsig] () Robust Signature Selection for Survival Outcomes
[SurvRank] ()

### Penalization of regularization
* {Boruta] () An all relevant feature selection wrapper algorithm. It finds relevant features by comparing original attributes' importance with importance achievable at random, estimated using their permuted copies.
* [c060] () Inference for Lasso and Elastic-Net Regularized Cox and Generalized Linear Models
* [FeaLect] () Scores Features for Feature Selection
* [fscaret] () Automated Feature Selection from 'caret'
* [Fselector] () Attribute subset selection is the process of identifying and removing as much of the irrelevant and redundant information as possible. rf
* [FWDselect] select the best model or best subset of variables using different types of data (binary, Gaussian or Poisson) and applying it in different contexts (parametric or non-parametric).
* [glmnet] () Lasso and Elastic-Net Regularized glm, for glm and survival
* [glmulti] () for interactions
* [meifly] () Exploratory model analysis. Fit and graphical explore ensembles of linear models
* [penalized] Penalized Estimation in GLMs and in the Cox Model. Fitting possibly high dimensional
* [relaxnet] () Relaxation of glmnet models for lm
* [shrink] () Global, Parameterwise and Joint Shrinkage Factor Estimation

## Data sources 

Check [CRAN Task View on Web technologies](http://cran.r-project.org/web/views/WebTechnologies.html).

## Data management

Check out this great cheatsheet: [Data wrangling with dplyr and tidyr](http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

* [rio]() A Swiss-Army Knife for Data I/O
* [tidyr]() Reshape data
* [reshape2]() Reshape data from long to wide format and vice versa
* [dplyr]() Data wrangling
* [data.table]() Tools for managing data frames
* [gdata]() Data manipulation
* [Hmisc]() Frank Harrell's miscellaneous tools 
* [Kmisc]() Data reshaping, table and plot generation from RMarkdown
* [lubridate]() Dates and times
* [multitable]() Manipulate multiple arrays
* [datacheck]() Tools for checking data consistency
* [pastecs] stat.desc
* [tabplot]() Large datasets viz.
* [tabplotd3]() Interactive
* [tableplot]()
* [taRifx](http://cran.r-project.org/web/packages/taRifx/index.html) Useful functions
* [DescTools](http://cran.r-project.org/web/packages/DescTools/index.html) Many useful functions
* [summarytools]() Quickly summarize dataframes (inc. markdown output)

## General statistics

### Ordination & Multivariate Analysis

Check also [Environmetrics](http://cran.r-project.org/web/views/Environmetrics.html) and [Multivariate](http://cran.r-project.org/web/views/Multivariate.html) CRAN Task Views.

* [vegan]()
* [ade4](http://cran.r-project.org/web/packages/ade4/index.html) Multivariate data analysis and display
* [dave]() Data Analysis in Vegetation Ecology
* [ecodist]() Dissimilarity-based analysis (ordination, Mantel tests...)
* [labdsv]() Includes plotting functions
* [mvabund]() Analysing multivariate data (upscaling from individual species models)
* [boral]() Bayesian ordination and regression analysis
* [eigenprcomp](http://cran.r-project.org/web/packages/eigenprcomp/) Computes confidence intervals for the proportion explained by the first 1,2,k principal components

### Survival analysis
* [survival]()
* [survMisc]()
* [coxme]() Mixed-effects cox regression
* [rawr]() Plotting functions: kmplot & ggsurv

### Regression tools

* [aod]() Analysis of Overdispersed data
* [apricom] () a Priori Comparison of Regression Modelling Strategies
* [arm]() Gelman's package: includes bayesglm, sim, coefplot...
* [bbmle]() Tools for MLE
* [binomTools]() Diagnostics for binomial regression
* [car]() boxCox, anova (for nested models), dataEllipse 
* [coefplot]() Plot model coefficients
* [confReg]() Estimating confidence of individual regression predictions
* [COUNT]() Regression models for count data (Poisson, Negative Binomial)
* [DAAG]() Some regression tools from the book 'Data Analysis and Graphics using R'
* [dhglm]() Hierarchical GLMs with random effects in both the mean and dispersion components
* [dynlm]() Dynamic linear models and time series regression
* [earth]() Multivariate Adaptive Regression Splines
* [effects]() Displays effects estimated from regression models
* [emdbook]() Tools from 'Ecological Models and Data' (inc. several plotting functions)
* [fit.models]() Compare results from different models
* [FME]() Modelling tools
* [gam]() Generalised Additive Models (GAMs)
* [gamm4]() GAMMs
* [gbm]() Generalised Boosted regression models
* [gee]() Generalized Estimating Equations
* [glm2]() To fit GLMs with convergence problems
* [gnm]() Generalized nonlinear models
* [heatmapFit]() Checking logistic regression goodness of fit
* [hier.part]() Variance partitioning to assess 'importance' of predictors. See also `relaimpo`.
* [Hmisc]() areg (Additive Regression with Optimal Transformations on Both Sides using Canonical Variates), aregImpute,redun (redundancy analysis), transcan
* [nlme]() Mixed models
* [lme4]() Mixed models
* [pamm]() Power analysis for mixed models
* [odprism]() Power analysis for mixed models
* [likelihood]() Maximum Likelihood Estimation
* [lmtest]() Diagnostic checks for linear regression
* [MARSS]() Multivariate Autoregressive State-Space Modeling
* [MASS] 
* [MCMCglmm]() Mixed models fitted by MCMC
* [mgcv]() GAM fitting
* [miscF]() Multivariate Normal regression, spatial Bayesian mixed models, piecewise regression...
* [mlogit]() Multinomial regression
* [mvinfluence]() Influence Measures and Diagnostic Plots for Multivariate Linear Models
* [msm]() Multi-state Markov and hidden Markov models in continuous time
* [PCovR]() Principal Covariates Regression (Reducing collinear predictor variables to a few components and regressing on them)
* [HLMdiag]() Diagnostic tools for hierarchical models (fitted with lme4)
* [stremo]() Learning Structural Equation Models
* [rockchalk]() Regression Estimation and Presentation
* [R2STATS]() GUI for fitting and comparing GLM and GLMM in R
* [LMERConvenienceFunctions]()
* [R2admb]() 
* [rms]() calibrate, fastbw, plsmo, Rq (quantreg), rrcov, validate
* [Zelig]()


### Bayesian/MCMC
Check also [Bayesian CRAN Task View](http://cran.r-project.org/web/views/Bayesian.html).

* [bayess]() Funcions used in the book 'Bayesian essentials with R'
* [blme]() Bayesian multilevel models
* [BMA]() Model averaging
* [BMS] 
* [dclone]() Data cloning and MCMC tools (inc. JAGS functions)
* [dcmle]() Hierarchical models through data cloning
* [dlm]() Dynamic models and MCMC tools
* [dlmodeler]() State-space modelling
* [sspir]() State-space models
* [MCMCglmm]() Mixed models fitted by MCMC
* [RSGHB]() Hierarchical Bayes models
* [bayespref]() Analysis of count data
* [predcomps](https://github.com/dchudz/predcomps) Average Predictive Comparisons

#### MCMC diagnostics
* [coda]() MCMC output analysis
* [boa]() Analyses of MCMC output (like `coda`)
* [ggmcmc]() Graphic analysis of MCMC output
* [mcmc]()
* [mcmcmplots]() Plot MCMC output
* [plotMCMC]() Diagnostic plots
* [bmk]() MCMC diagnostics
* [scapeMCMC]() MCMC diagnostic plots
* [superdiag]() testing MCMC noncovergence

#### Generic MCMC samplers
* [adaptMCMC](http://cran.r-project.org/web/packages/adaptMCMC/index.html) Generic MCMC sampler
* [BRugs]() Interface to OpenBUGS
* [BayesX]() Structured Additive Regression
* [R2BayesX]()
* [rjags]()
* [runjags]()
* [R2jags]()
* [R2OpenBUGS]()
* [R2WinBUGS]()
* [rstan]()
* [filzbach]()
* [iBUGS]() Interface to BUGS/JAGS
* [rube](http://stat.cmu.edu/~hseltman/rube/)
* [INLA]() Integrated Nested Laplace Approximation
* [LaplacesDemon]() 
* [LearnBayes]() 
* [MCMCpack]() MCMC samplers
* [MHAdative]() MCMC sampler
* [glmmBUGS]()
* [datalist](http://cran.r-project.org/web/packages/datalist/index.html)

#### Spatial Bayes
* [CARBayes]() Spatial models with CAR
* [spBayes]() spatial Bayes
* [geoCount](http://cran.r-project.org/web/packages/geoCount/index.html) generalized linear spatial models

#### ABC
* [abc](http://cran.r-project.org/web/packages/abc/index.html) Approximate Bayesian Computation
* [easyABC]() Approximate Bayesian Computation

## Plotting & Visualisation
Check also [CRAN Task View on Graphics](http://cran.r-project.org/web/views/Graphics.html).
* [denstrip]() Plotting distributions (w uncertainty)
* [visualize]() Graph Probability Distributions
* [fanplot]() Visualise sequential probability distributions
* [diagram]() Networks, flow diagrams, etc
* [beanplot]() Bean plots
* [vioplot]() Violin plots
* [viopoints]() 1-D Scatter Plots with Jitter Using Kernel Density Estimates
* [dagR]() Directed Acyclic graphs (DAGs)
* [effects]() Displays effects estimated from regression models
* [coefplot]() Plot model coefficients
* [plotmo]() Plot model responses
* [corrgram]() Plot correlation matrix
* [gclus]() Clustering graphics
* [vcd]() Viz categorical data
* [extracat]() Viz categorical data
* [plot3d](http://cran.r-project.org/web/packages/plot3D/index.html) Plotting multi-dimensional data
* [VizOR](http://cran.r-project.org/web/packages/VizOR/index.html) visualization tools for complex observational data
* [GrapheR]() GUI for base plots


### GGPLOT2

* [ggplot2]()
* [GGally]() extension to ggplot
* [ggsubplot]() Embedding subplots within plots
* [ggthemes]() Extra themes, scales and geoms for ggplot
* [gplot2bdc](https://github.com/briandconnelly/ggplot2bdc)
* [ggtern](http://www.ggtern.com/) Ternary diagrams
* [ggthemr](https://github.com/cttobin/ggthemr) Extra themes for ggplot2
* [plotly](https://github.com/ropensci/plotly) R interface to plotly
* [googleVis]() Using google chart tools
* [rCharts]() Interactive charts
* [lattice]() Multivariate plots
* [manipulate]() Interactive plots
* [misc3d]() 3D plots
* [mvtsplot]() Multivariate time series plot
* [pca3d]() Three dimensional PCA plots
* [longCatEDA]() Plot Categorical Longitudinal and Time-Series Data
* [squash]() Color-based plots for multivariate visualization
* [tourr]() 
* [latticist]() GUI for graphic exploratory data analysis using lattice
* [tfplot]() Plot time series
* [pathdiagram](http://cran.r-project.org/web/packages/pathdiagram/) 
* [RIGHT]() Interactive graphics via HTML
* [clickme](https://github.com/nachocab/clickme) Interactive plots

* [animation]() Create animations

* [calibrate]() Axes calibration
* [labeling]() Axis labeling
* [directlabels]() Labels for multicolor plots. See also `Hmisc:::labcurve`.
* [gplots]() Useful plotting tools
* [magicaxis]() Pretty scientific plots (e.g. log scales)
* [PlotRegionHighlighter]() Creates an envelope that surrounds a set of points
* [compactr](http://cran.us.r-project.org/web/packages/compactr/index.html) Plots with compact axis notation
* [plotflow](https://github.com/trinker/plotflow) Useful plotting functions
* [sendplot]() Interactive plots with tool-tip content
* [zoom]() Allow to zoom/navigate in any plot.
* [epade]() Easy plots
* [prettyGraphs]() Publication-quality graphics.
* [scagnostics]() Scatterplot diagnostics


### Colour
* [colorRamps]() Colour palettes
* [RColorBrewer]()
* [colorspace]() HCL (perceptually-based) palettes
* [colortools]()
* [plotKML]() Colour palettes for mapping
* [gplots]() Rich.colors palettes

* [dataview]()
* [tabplot]() Large datasets viz.
* [tabplotd3]() Interactive
* [R2SWF]() Convert R graphics to Flash
* [sendplot]() Send interactive plots with tooltip content
* [sjPlot]()
* [squash]() Color-based plots for multivariate visualization

## Reproducible Research - Report generation
Check also CRAN Task View on [Reproducible Research](http://cran.r-project.org/web/views/ReproducibleResearch.html).
* [brew]()
* [knitr]() Dynamic report generation
* [knitrBootstrap](https://github.com/jimhester/knitrBootstrap) create bootstrap styled HTML reports from Rmarkdown
* [reports]() writing reports and presentations
* [repmis]()
* [rapport](http://cran.r-project.org/web/packages/rapport/index.html) report templating system
* [pander]() Exploits pandoc to convert among multiple formats
* [stargazer]() Easily create tables with regression outputs (directly from model objects)
* [rtf](http://cran.r-project.org/web/packages/rtf/index.html) Produce Rich Text Format documents from R
* [R2HTML](http://cran.r-project.org/web/packages/R2HTML/index.html) HTML reports from R
* [xtable](http://cran.r-project.org/web/packages/xtable/index.html) Export R objects to HTML tables
* [R2wd]() Write MS-Word documents from R
* [rmarkdown]()
* [sjPlot]()
* [Rgitbook](https://github.com/jbryer/Rgitbook)
* [table1xls](http://cran.r-project.org/web/packages/table1xls/index.html) Summary tables in Excel format.
* [DescTools](http://cran.r-project.org/web/packages/DescTools/index.html)
* [rctrack](http://www.stjuderesearch.org/site/depts/biostats/rctrack)

## Parallelisation & Big Data
Check also [CRAN Task View on High Performance Computing](http://cran.r-project.org/web/views/HighPerformanceComputing.html).
* [ff]() Big data management. See also package `ffbase`
* [batch]() Batching routines in parallel
* [bigdata]()


## Ecological analyses (miscellaneous)
Check also [Environmetrics CRAN Task View](http://cran.r-project.org/web/views/Environmetrics.html).
* [betapart]() Beta diversity
* [BiodiversityR]() GUI for biodiversity, suitability and community ecology analyses
* [cheddar]() Analysis and visualisation of community data
* [coexist]() Modelling species coexistence
* [DSpat]() Distance Sampling
* [fossil]() Species richness, species-area curves, beta-diversity
* [indicspecies]() Assess associations between different species and sites (e.g. indicator species)
* [IPMpack]() Integral Projection Models
* [marked]() Mark-recapture analysis
* [MBI]() Multiple Beta Diversity indices
* [rmeta]() Meta-analysis
* [neighlikeli]() Neighborhood models
* [earlywarnings]()
* [MAR1]() Multivariate Autoregressive Modeling for Analysis of Community Time-Series Data
* [ncbit]() retrieve NBCI taxonomic data
* [spacodiR]() Spatial and Phylogenetic Analysis of Community Diversity
* [Reol](http://cran.r-project.org/web/packages/Reol/) Interface to Encyclopedia of Life
* [SPECIES]() Species richness and diversity analysis
* [BayesComm]() Bayesian multivariate binary regression models for analysis of ecological communities
* [pom]() Patch occupancy models
* [capwire]() Population size estimation from non-invasive sampling
* [vegclust]() Fuzzy clustering of vegetation data
* [popbio]()
* [demoniche](http://demoniche.r-forge.r-project.org/) Spatially-explicit demographic modelling
* [BEDASSLE]() Disentangles the effects of geographic and ecological isolation on genetic differentiation.
* [rphylopic](https://github.com/sckott/rphylopic) Organisms silhouettes
* [GSIF]() Global Soil Information
* [Rarity]() Rarity indices
* [taxize]() Taxonomy etc.
* [Taxonstand]()
* [sExtinct]() Extinction analysis based on sightings
* [BEDASSLE](http://cran.r-project.org/web/packages/BEDASSLE/) Disentangles the effects of geographic and ecological isolation on genetic differentiation
* [ecomodtools]() Simulation models (inc. dispersal) 
* [comclim](http://cran.r-project.org/web/packages/comclim/index.html) Community climate statistics
* [kernelPop](http://cran.r-project.org/web/packages/kernelPop/index.html) Spatially explicit population genetic simulations
* [siplab](http://cran.r-project.org/web/packages/siplab/index.html) spatially explicit individual-based vegetation models.


## Miscellaneous
* [digitize]() Extract data from plots
* [downloader]() Download files from internet
* [hwriter]() Outputs R objects in HTML format
* [installr]() Automatically update R
* [mail]() Send email notifications from R
* [sendmailR]()
* [mosaic]()
* [audiolyzR]() Creates audio representations of common plots
* [WebDevelopR]() Web development
* [ProjectTemplate]() 
* [gpk]() Datasets for educational uses
* [NCmisc](http://cran.r-project.org/web/packages/NCmisc/) 
* [PubMedWordcloud]() Create wordcloud with abstracts.
* [alm]() Altmetrics
* [rAltmetric]() Retrieves data from altmetrics.com
* [RMendeley]()
* [rcrossref]()
* [RefManageR]() Bibliography Management.
* [refnet]() Reads and works with data from ISI Web of Knowledge
* [scholar]() 
* [slidify]()
* [sos]() Search R packages
* [source.gist]()
* [twitteR]()
* [DescTools](http://cran.r-project.org/web/packages/DescTools/index.html)


## R programming
* [codetools]() Code analysis tools
* [compiler]() Compile R code (e.g. a function) to speed it up
* [devtools]()
* [formatR]() Format and tidy R code
* [gtools]() Useful functions (e.g. mixedsort)
* [inline]() Define functions in C code within R
* [iterators]() Tools for iteration on many different types of objects (see also `itertools`)
* [Kmisc]() Data reshaping, table and plot generation from RMarkdown
* [operators]() Additional operators
* [simFrame]() A framework to work with simulations
* [simSummary]()
* [staticdocs]() Create webpage with package documentation
* [testit]() Testing R packages
* [testthat]() Testing R code
* [tester]() Test characteristics of R objects
* [assertthat]().
* [httr]() Working with URLs and HTTP
* [RCurl]() HTTP interface
* [stringr]()
* [Rd2Roxygen]()
* [Rxoygen2]()
* [scrapeR]()
* [aprof](http://cran.r-project.org/web/packages/aprof/index.html) Profiling code and visualizing results to evaluate where is best to focus code optimization.
* [regex](https://github.com/richierocks/regex) Regular expressions made easier.
